import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Fragment } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rapid Showroom",
  description: "Generated by create next app",
};

export default function BuycarLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Box display={"flex"} flexDirection={"column"} justifyContent={"center"} paddingX={6} paddingY={4}>
      <Box display={"flex"} justifyContent={"center"}>
        <Box marginTop={8}>
          <h1>Showroom</h1>
        </Box>
      </Box>
      {children}
    </Box>
  );
}
